### ISSUE TITLE
Kaggle Crack Dataset을 이용한 모델 실험

### ISSUE THREAD

**Issue by jeongjae96** [jeongjae96/soteria8-crack-detection#3]
## Description

- 기업 데이터를 받기 전, [Kaggle Crack Dataset](https://www.kaggle.com/datasets/yatata1/crack-dataset/)을 이용해 object detection, instance segmentation 모델을 돌려볼 수 있는 프레임워크에 익숙해지기

## Tasks

- [ ] EDA
- [ ] [SuperGradients](https://www.supergradients.com/)
- [ ] [MMdetection](https://mmdetection.readthedocs.io/en/latest/)
- [ ] [MMsegmentation](https://mmsegmentation.readthedocs.io/en/latest/)
- [ ] [Detectron2](https://github.com/facebookresearch/detectron2)
- [ ] [Ultralytics](https://www.ultralytics.com/)
- [ ] [Pytorch Segmentation](https://github.com/qubvel/segmentation_models.pytorch)
- [ ] [Torchvision](https://pytorch.org/vision/stable/index.html)
